version: 1

formatters:
  custmoFormatter:
    format: '[%(asctime)s]%(levelname)s - %(filename)s#%(funcName)s:%(lineno)d: %(message)s'
    datefmt: 'Y/%m/%d %H:%M:%S'

loggers:
  file:
    handlers: [fileRotatingHandler]
    level: DEBUG
    qualname: file
    propagate: no

handlers:
  fileRotatingHandler:
    formatter: custmoFormatter
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    filename: /usr/local/gunicorn/log/application.log
    encoding: utf8
    when: 'D'
    interval: 1
    backupCount: 14

root:
  level: DEBUG
  handlers: [fileRotatingHandler]