version: '2'
services:
    web:
        restart: always
        build:
            context: ./WebApp/
            dockerfile: Dockerfile
        ports:
            - 3000:8080
        links:
            - db:mysql_container
        volumes:
            - ./WebApp/src:/var/app/src
    db:
        build:
            context: ./MySQL/
            dockerfile: Dockerfile
        ports:
            - 3306:3306
        volumes:
            - ./MySQL/mysql_conf:/etc/mysql/conf.d
